Add GitHub labels
microsoft/vscode-python-debugger pull request #15
Opened 2023-06-07 23:19 UTC by paulacamargo25

Closed: #12

2023-06-07 23:38 UTC, karthiknadig commented on package.json
> +    "vsce": "^2.15.0",
You should be using `@vscode/vsce`

2023-06-12 21:46 UTC, karthiknadig requested changes

2023-06-12 21:46 UTC, karthiknadig commented on .github/workflows/pr-check.yml
> +        python: ['3.7', '3.8', '3.9', '3.10', '3.11-dev']
```suggestion
        python: ['3.7', '3.8', '3.9', '3.10', '3.11']
```

2023-06-12 21:46 UTC, karthiknadig commented on .github/workflows/pr-check.yml
> +  NODE_VERSION: 14.19.0
```suggestion
  NODE_VERSION: 16.17.0
```

2023-06-12 21:46 UTC, karthiknadig commented on .github/workflows/push-check.yml
> +  NODE_VERSION: 14.19.0
```suggestion
  NODE_VERSION: 16.17.0
```

2023-06-12 21:46 UTC, karthiknadig commented on .github/workflows/push-check.yml
> +        python: ['3.7', '3.8', '3.9', '3.10']
```suggestion
        python: ['3.7', '3.8', '3.9', '3.10', '3.11']
```

2023-06-12 21:46 UTC, karthiknadig commented on noxfile.py
> +def lint(session: nox.Session) -> None:
For future, this can be used for linting the entire extension.

2023-06-13 00:55 UTC, karthiknadig approved these changes

2023-06-13 01:04 UTC, merged

2023-07-10 14:07 UTC, karrtikr reviewed
This PR is still using an older way to use Github actions, please look at the Python extension and update the code accordingly.

2023-07-10 14:07 UTC, karrtikr commented on .github/workflows/issue-labels.yml
> +            }
We should be using microsoft/vscode-github-triage-actions