Add auto start browser as default value
microsoft/vscode-python-debugger pull request #229
Opened 2024-02-22 01:58 UTC by paulacamargo25

2024-02-22 02:39 UTC, bhavyaus requested changes
Blocking on the warnings in `flaskLaunch.unit.test.ts`. Feel free to dismiss my review with a reason if the warnings are ignorable.

2024-02-22 19:48 UTC, paulacamargo25 commented
> Blocking on the warnings in `flaskLaunch.unit.test.ts`. Feel free to dismiss my review with a reason if the warnings are ignorable.

Thanks for the review @bhavyaus, yes the warnings are ignorables. So dont worry.

2024-02-22 21:22 UTC, bhavyaus approved these changes

2024-02-23 00:11 UTC, karthiknadig approved these changes

2024-02-23 01:04 UTC, merged