Add variable presentation
microsoft/vscode-python-debugger pull request #433
Opened 2024-08-06 21:13 UTC by paulacamargo25

Closed: https://github.com/microsoft/vscode-python-debugger/issues/165
- Add debugVariablePresentation as a setting so the user can set this value globally.
- Add variablePresentation in debug config so the user can set it in the launch.json.
- Update the config order alphabetically.
- Create test.

2024-08-06 21:28 UTC, DonJayamanne submitted a review, later dismissed

2024-08-07 06:48 UTC, karthiknadig commented on src/extension/debugger/configuration/resolvers/attach.ts
> +        if (debugConfiguration.variablePresentation == undefined) {
The `==` should be `===`

2024-08-07 06:48 UTC, karthiknadig commented on src/extension/debugger/configuration/resolvers/launch.ts
> +        if (debugConfiguration.variablePresentation == undefined) {
Same here

2024-08-07 06:49 UTC, karthiknadig requested changes
Minor changes. See comments below.

2024-11-14 02:55 UTC, max09000-tec approved these changes

2024-11-14 02:55 UTC, max09000-tec commented on package.json
>                  },
/

2025-01-16 21:32 UTC, closed without merging